version: '3.1'

services:
    db:
        image: mysql:8.0
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3308:3306
        volumes:
            - db:/var/lib/mysql
    app:
        build:
            context: ./
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html

    webserver:
        image: nginx
        working_dir: /application
        depends_on:
            - app
        links:
            - app
        volumes:
            - ./public:/var/www/html/public
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80
            - 4433:443

volumes:
    db:
